const express=require("express"),session=require("express-session"),bcrypt=require("bcryptjs"),Database=require("better-sqlite3");
const path=require("path"),fs=require("fs");
const dbPath=process.env.DB_PATH||path.join(__dirname,"data","storyverse.db");
fs.mkdirSync(path.dirname(dbPath),{recursive:true});
const db=new Database(dbPath),app=express();
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,bio TEXT DEFAULT '',avatar TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS stories(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL,description TEXT DEFAULT '',genre TEXT DEFAULT 'Other',content TEXT NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS votes(user_id INTEGER NOT NULL,story_id INTEGER NOT NULL,PRIMARY KEY(user_id,story_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(story_id) REFERENCES stories(id));`);
app.use(express.json());app.use(express.urlencoded({extended:true}));
app.set("trust proxy",1);
app.use(session({secret:process.env.SESSION_SECRET||"change-this-secret",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production"}}));
app.use(express.static(path.join(__dirname,"public")));
const me=(req,res,next)=>{if(!req.session.userId)return res.status(401).json({error:"Login required"});next()};
app.post("/api/register",(req,res)=>{try{let {username,password}=req.body;if(!username||!password||username.length<3||password.length<6)return res.status(400).json({error:"Username: 3+ chars. Password: 6+ chars."});let hash=bcrypt.hashSync(password,10);let x=db.prepare("INSERT INTO users(username,password) VALUES(?,?)").run(username.trim(),hash);req.session.userId=x.lastInsertRowid;res.json({ok:true})}catch(e){res.status(400).json({error:"Username already exists"})}});
app.post("/api/login",(req,res)=>{let u=db.prepare("SELECT * FROM users WHERE username=?").get(req.body.username);if(!u||!bcrypt.compareSync(req.body.password,u.password))return res.status(401).json({error:"Wrong username or password"});req.session.userId=u.id;res.json({ok:true})});
app.post("/api/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/me",(req,res)=>{if(!req.session.userId)return res.json({user:null});let u=db.prepare("SELECT id,username,bio,avatar FROM users WHERE id=?").get(req.session.userId);res.json({user:u})});
app.get("/api/stories",(req,res)=>res.json(db.prepare(`SELECT s.id,s.title,s.description,s.genre,s.created_at,u.username,COUNT(v.user_id) votes FROM stories s JOIN users u ON u.id=s.user_id LEFT JOIN votes v ON v.story_id=s.id GROUP BY s.id ORDER BY s.created_at DESC`).all()));
app.get("/api/stories/:id",(req,res)=>{let s=db.prepare(`SELECT s.*,u.username,COUNT(v.user_id) votes FROM stories s JOIN users u ON u.id=s.user_id LEFT JOIN votes v ON v.story_id=s.id WHERE s.id=? GROUP BY s.id`).get(req.params.id);if(!s)return res.sendStatus(404);res.json(s)});
app.post("/api/stories",me,(req,res)=>{let {title,description,genre,content}=req.body;if(!title||!content)return res.status(400).json({error:"Title and story are required"});let x=db.prepare("INSERT INTO stories(user_id,title,description,genre,content) VALUES(?,?,?,?,?)").run(req.session.userId,title,description||"",genre||"Other",content);res.json({id:x.lastInsertRowid})});
app.post("/api/stories/:id/vote",me,(req,res)=>{let sid=+req.params.id,uid=req.session.userId;let exists=db.prepare("SELECT 1 FROM votes WHERE user_id=? AND story_id=?").get(uid,sid);if(exists)db.prepare("DELETE FROM votes WHERE user_id=? AND story_id=?").run(uid,sid);else db.prepare("INSERT INTO votes(user_id,story_id) VALUES(?,?)").run(uid,sid);res.json({voted:!exists,votes:db.prepare("SELECT COUNT(*) n FROM votes WHERE story_id=?").get(sid).n})});
app.put("/api/profile",me,(req,res)=>{db.prepare("UPDATE users SET bio=?,avatar=? WHERE id=?").run(req.body.bio||"",req.body.avatar||"",req.session.userId);res.json({ok:true})});
app.get("/api/users/:username",(req,res)=>{let u=db.prepare("SELECT id,username,bio,avatar FROM users WHERE username=?").get(req.params.username);if(!u)return res.sendStatus(404);let stories=db.prepare(`SELECT s.id,s.title,s.description,s.genre,COUNT(v.user_id) votes FROM stories s LEFT JOIN votes v ON v.story_id=s.id WHERE s.user_id=? GROUP BY s.id ORDER BY s.created_at DESC`).all(u.id);res.json({...u,stories})});
app.listen(process.env.PORT||3000,()=>console.log("StoryVerse running"));
